version: "3.6"

services:
    rabbitmqcompose:
        image: rabbitmq:3.10-management
        container_name: rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ./dados:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=vitor
            - RABBITMQ_DEFAULT_PASS=vitor
